version: '3.0'
services:
  builder:
    build: .
    container_name: builder
    privileged: true
    volumes:
      - $PWD/src:/dectalk/src:ro
      - $PWD/build:/dectalk/build:rw
      - $PWD/scripts:/scripts:ro
